# fly.toml app configuration file generated for bender-bot on 2024-09-11T19:52:30-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bender-bot'
primary_region = 'iad'

[build]

[env]
  IS_ON_FLY=true

[[mounts]]
  source = 'bender_data'
  destination = '/data'
  initial_size = '10gb'

[[services]]
  protocol = ''
  internal_port = 0
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  ports = []
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

  